highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
#baseurl: /vitae/
title: Big Bear Computer Repair
name: Big Bear
email: enquiry@bigbearcomputerrepair.co.uk
email_full: mailto:enquiry@bigbearcomputerrepair.co.uk
website: dreveritt.github.io
website_full: http://www.bigbearcomputerrepair.co.uk
github: dreveritt
twitter: twitter
#tel: +44 0000 000000
#tel_full: tel:+440000000000

address: Retford, Notts, United Kingdom
postcode: DN22 7RQ
city: Retford
country: United Kingdom
google_analytics: UA-49478194-4

# needed for travis-ci build
exclude: [vendor]
